name: localpkg
description: My personal local package for all utilities.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.2.0
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  quick_navbar: ^1.0.4
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  icons_plus: ^5.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

  flutter_test:
    sdk: flutter
