name: personal
description: My personal local package for all utilities
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

  flutter_test:
    sdk: flutter
